[platformio]
default_envs = core2
src_dir = src

[env:core2]
platform = platformio/espressif32
framework = arduino
board = m5stack-core2
monitor_speed = 115200
upload_port = auto
build_flags =
  -DCORE2_APP_NAME=\"dooard\"
lib_deps =
  m5stack/M5Unified @ ^0.2.7
  bblanchon/ArduinoJson @ ^7.0.4

[env:native]
platform = native
test_framework = unity
