[platformio]
default_envs = core2
src_dir = src

[env]
lib_deps =
  bblanchon/ArduinoJson @ ^7.0.4

[env:core2]
platform = platformio/espressif32
framework = arduino
board = m5stack-core2
board_build.partitions = default_8MB.csv
board_build.flash_mode = qio
extra_scripts = pre:scripts/build_version.py
monitor_speed = 115200
upload_port = auto
build_flags =
  -DCORE2_APP_NAME=\"dooard\"
lib_deps =
  ${env.lib_deps}
  m5stack/M5Unified @ ^0.2.7

[env:native]
platform = native
test_framework = unity
